input [7:0] minuend;
input [7:0] subtrahend;
output [7:0] difference;

wire inv_subtrahend_7;
wire inv_subtrahend_6;
wire inv_subtrahend_5;
wire inv_subtrahend_4;
wire inv_subtrahend_3;
wire inv_subtrahend_2;
wire inv_subtrahend_1;
wire inv_subtrahend_0;

wire negator_carry_0;
wire negator_carry_1;
wire negator_carry_2;
wire negator_carry_3;
wire negator_carry_4;
wire negator_carry_5;
wire negator_carry_6;
wire negator_carry_7;

wire neg_subtrahend_7;
wire neg_subtrahend_6;
wire neg_subtrahend_5;
wire neg_subtrahend_4;
wire neg_subtrahend_3;
wire neg_subtrahend_2;
wire neg_subtrahend_1;
wire neg_subtrahend_0;

wire carry;
wire temp;
wire temp2;
wire neg_carry;

assign inv_subtrahend_7 = ~ subtrahend[7];
assign inv_subtrahend_6 = ~ subtrahend[6];
assign inv_subtrahend_5 = ~ subtrahend[5];
assign inv_subtrahend_4 = ~ subtrahend[4];
assign inv_subtrahend_3 = ~ subtrahend[3];
assign inv_subtrahend_2 = ~ subtrahend[2];
assign inv_subtrahend_1 = ~ subtrahend[1];
assign inv_subtrahend_0 = ~ subtrahend[0];

assign negator_carry_0 = inv_subtrahend_0;
assign negator_carry_1 = negator_carry_0 & inv_subtrahend_1;
assign negator_carry_2 = negator_carry_1 & inv_subtrahend_2;
assign negator_carry_3 = negator_carry_2 & inv_subtrahend_3;
assign negator_carry_4 = negator_carry_3 & inv_subtrahend_4;
assign negator_carry_5 = negator_carry_4 & inv_subtrahend_5;
assign negator_carry_6 = negator_carry_5 & inv_subtrahend_6;
assign negator_carry_7 = negator_carry_6 & inv_subtrahend_7;

assign neg_subtrahend_0 = ~ inv_subtrahend_0;
assign neg_subtrahend_1 = negator_carry_0 ~^ subtrahend[1];
assign neg_subtrahend_2 = negator_carry_1 ~^ subtrahend[2];
assign neg_subtrahend_3 = negator_carry_2 ~^ subtrahend[3];
assign neg_subtrahend_4 = negator_carry_3 ~^ subtrahend[4];
assign neg_subtrahend_5 = negator_carry_4 ~^ subtrahend[5];
assign neg_subtrahend_6 = negator_carry_5 ~^ subtrahend[6];
assign neg_subtrahend_7 = negator_carry_6 ~^ subtrahend[7];

assign difference[0] = minuend[0] ^ neg_subtrahend_0;
assign carry = minuend[0] & neg_subtrahend_0;
assign neg_carry = ~ carry;
assign difference[1] = minuend[1] ^ neg_subtrahend_1;
assign temp = minuend[1];
assign temp = temp & neg_subtrahend_1;
assign temp2 = carry & difference[1];
assign difference[1] = difference[1] ~^ neg_carry;
assign carry = temp | temp2;
assign neg_carry = ~ carry;
assign difference[2] = minuend[2] ^ neg_subtrahend_2;
assign temp = minuend[2] & neg_subtrahend_2;
assign temp2 = carry & difference[2];
assign difference[2] = difference[2] ~^ neg_carry;
assign carry = temp | temp2;
assign difference[3] = minuend[3] ^ neg_subtrahend_3;
assign temp = minuend[3] & neg_subtrahend_3;
assign temp2 = carry & difference[3];
assign difference[3] = difference[3] ^ carry;
assign carry = temp | temp2;
assign difference[4] = minuend[4] ^ neg_subtrahend_4;
assign temp = minuend[4] & neg_subtrahend_4;
assign temp2 = carry & difference[4];
assign difference[4] = difference[4] ^ carry;
assign carry = temp | temp2;
assign difference[5] = minuend[5] ^ neg_subtrahend_5;
assign temp = minuend[5] & neg_subtrahend_5;
assign temp2 = carry & difference[5];
assign difference[5] = difference[5] ^ carry;
assign carry = temp | temp2;
assign difference[6] = minuend[6] ^ neg_subtrahend_6;
assign temp = minuend[6] & neg_subtrahend_6;
assign temp2 = carry & difference[6];
assign difference[6] = difference[6] ^ carry;
assign carry = temp | temp2;
assign neg_carry = ~ carry;
assign difference[7] = minuend[7] ^ neg_subtrahend_7;
assign temp = minuend[7] & neg_subtrahend_7;
assign temp2 = carry & difference[7];
assign difference[7] = difference[7] ~^ neg_carry;
assign carry = temp | temp2;
assign carry = ~ carry;